server:
  port: 8302

spring:
  application:
    name: server02  # 应用程序名称，后面会在消费者中用到

eureka:
  instance:
    preferIpAddress: true # 访问路径是否显示IP
    instance-id: ${spring.application.name}-${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka  # 注册中心 eureka 访问地址
