server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        # 测试【以下路由断言可组合使用】
#        - id: test_route
#          uri: http://www.ityouknow.com
#          predicates:
#            - Path=/spring-cloud
        # 时间匹配
#        - id: time_route
#          uri: http://ityouknow.com
#          predicates:
##            - Before=2019-11-26T09:00:00+08:00[Asia/Shanghai]
#            - Between=2019-11-25T09:00:00+08:00[Asia/Shanghai], 2019-11-28T09:00:00+08:00[Asia/Shanghai]
        # Cookie 匹配
#        - id: cookie_route
#          uri: http://ityouknow.com
#          predicates:
#            - Cookie=name, eric
        # Header 匹配
#        - id: header_route
#          uri: http://ityouknow.com
#          predicates:
#            - Header=X-Request-Id, \d+
        # Method 匹配
#        - id: method_route
#          uri: http://ityouknow.com
#          predicates:
#            - Method=GET
        # 请求路径匹配
#        - id: path_route
#          uri: http://ityouknow.com
#          predicates:
#            - Path=/foo/{segment} # 如：/foo/123, /foo/abc
        # 请求参数匹配
#        - id: query_route
#          uri: http://ityouknow.com
#          predicates:
#            - Query=abc # 请求参数中带有abc即可，如：http://localhost:8080?abc=111
#            - Query=abc, 123 # 参数名为abc，参数值为123，如：http://localhost:8080?abc=123
#            - Query=abc, do. # 参数值支持正则表达式，如：http://localhost:8080?abc=dog
        # ip 匹配
        - id: remoteAddr_route
          uri: http://ityouknow.com
          predicates:
            - RemoteAddr=192.168.3.79 # 本机ip为192.168.3.79
